version: '3.8'

services:
  mysql-db:
    image: mysql:latest
   # container_name: mysql_project
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump-hibernate-final.sql:/docker-entrypoint-initdb.d/dump.sql

  redis-cache:
    image: redis:latest
    # container_name: redis_project
    restart: unless-stopped
    #network_mode: "host"
    command: "redis-server --appendonly yes --loglevel warning --tcp-keepalive 0"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:


